COULEUR = "couleur"
PIECE = "piece"
ZONE = "zone"

ROUGE = "rouge"
VERT = "vert"
BLEU = "bleu"
JAUNE = "orange"

CARRE = "carré"
TRIANGLE = "triangle"
CERCLE = "cercle"
PENTAGON = "pentagone"

ZONE_0 = "Zone 0"
ZONE_1 = "Zone 1"
ZONE_2 = "Zone 2"
ZONE_3 = "Zone 3"


QR_CODE_VALUE_DICTIONARY = {
    "0": {COULEUR: ROUGE, PIECE: None, ZONE: ZONE_0},
    "1": {COULEUR: ROUGE, PIECE: None, ZONE: ZONE_1},
    "2": {COULEUR: ROUGE, PIECE: None, ZONE: ZONE_2},
    "3": {COULEUR: ROUGE, PIECE: None, ZONE: ZONE_3},

    "4": {COULEUR: VERT, PIECE: None, ZONE: ZONE_0},
    "5": {COULEUR: VERT, PIECE: None, ZONE: ZONE_1},
    "6": {COULEUR: VERT, PIECE: None, ZONE: ZONE_2},
    "7": {COULEUR: VERT, PIECE: None, ZONE: ZONE_3},

    "8": {COULEUR: BLEU, PIECE: None, ZONE: ZONE_0},
    "9": {COULEUR: BLEU, PIECE: None, ZONE: ZONE_1},
    "10": {COULEUR: BLEU, PIECE: None, ZONE: ZONE_2},
    "11": {COULEUR: BLEU, PIECE: None, ZONE: ZONE_3},

    "12": {COULEUR: JAUNE, PIECE: None, ZONE: ZONE_0},
    "13": {COULEUR: JAUNE, PIECE: None, ZONE: ZONE_1},
    "14": {COULEUR: JAUNE, PIECE: None, ZONE: ZONE_2},
    "15": {COULEUR: JAUNE, PIECE: None, ZONE: ZONE_3},

    "16": {COULEUR: None, PIECE: CARRE, ZONE: ZONE_0},
    "17": {COULEUR: None, PIECE: CARRE, ZONE: ZONE_1},
    "18": {COULEUR: None, PIECE: CARRE, ZONE: ZONE_2},
    "19": {COULEUR: None, PIECE: CARRE, ZONE: ZONE_3},

    "20": {COULEUR: None, PIECE: TRIANGLE, ZONE: ZONE_0},
    "21": {COULEUR: None, PIECE: TRIANGLE, ZONE: ZONE_1},
    "22": {COULEUR: None, PIECE: TRIANGLE, ZONE: ZONE_2},
    "23": {COULEUR: None, PIECE: TRIANGLE, ZONE: ZONE_3},

    "24": {COULEUR: None, PIECE: CERCLE, ZONE: ZONE_0},
    "25": {COULEUR: None, PIECE: CERCLE, ZONE: ZONE_1},
    "26": {COULEUR: None, PIECE: CERCLE, ZONE: ZONE_2},
    "27": {COULEUR: None, PIECE: CERCLE, ZONE: ZONE_3},

    "28": {COULEUR: None, PIECE: PENTAGON, ZONE: ZONE_0},
    "29": {COULEUR: None, PIECE: PENTAGON, ZONE: ZONE_1},
    "30": {COULEUR: None, PIECE: PENTAGON, ZONE: ZONE_2},
    "31": {COULEUR: None, PIECE: PENTAGON, ZONE: ZONE_3}

}