COLOR_DETECTOR_DEBUG = False
SHAPE_UTILS_DEBUG = False
SHAPE_DETECTOR_DEBUG = True
DETECT_ZONE_DEP_WORLD_DEBUG = False
DETECT_START_ZONE_DEBUG = False
DETECT_PICKUP_ZONE_DEBUG = False
DETECT_POINT_ZONE_DEP_DEBUG = False